// <auto-generated />
namespace RIABooks.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SupportEnums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SupportEnums));
        
        string IMigrationMetadata.Id
        {
            get { return "201212120257388_SupportEnums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
